-- supabase/migrations/001_initial_setup.sql
-- Create database schemas for Mokundo POS (Multi-Tenant Store model)

-- 1. STORES table (Store configuration)
CREATE TABLE public.stores (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    nama TEXT NOT NULL,
    alamat TEXT,
    logo TEXT,
    ppn NUMERIC DEFAULT 11,
    service_charge NUMERIC DEFAULT 0,
    receipt_header TEXT,
    receipt_footer TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security
ALTER TABLE public.stores ENABLE ROW LEVEL SECURITY;

-- 2. CATEGORIES table
CREATE TABLE public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id UUID REFERENCES public.stores(id) ON DELETE CASCADE NOT NULL,
    nama TEXT NOT NULL,
    urutan INTEGER DEFAULT 1,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;

-- 3. PRODUCTS table
CREATE TABLE public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id UUID REFERENCES public.stores(id) ON DELETE CASCADE NOT NULL,
    nama TEXT NOT NULL,
    kategori_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
    harga NUMERIC NOT NULL,
    hpp NUMERIC NOT NULL,
    stok INTEGER DEFAULT 0,
    sku TEXT NOT NULL,
    varian TEXT[] DEFAULT '{}'::TEXT[],
    gambar_url TEXT,
    threshold_stok INTEGER DEFAULT 5,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT unique_store_sku UNIQUE (store_id, sku)
);

ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- 4. SHIFTS table
CREATE TABLE public.shifts (
    id BIGINT PRIMARY KEY, -- Sync uses the locally generated ID
    store_id UUID REFERENCES public.stores(id) ON DELETE CASCADE NOT NULL,
    kasir_id BIGINT NOT NULL,
    kasir_nama TEXT NOT NULL,
    waktu_buka TIMESTAMP WITH TIME ZONE NOT NULL,
    waktu_tutup TIMESTAMP WITH TIME ZONE,
    modal_awal NUMERIC NOT NULL,
    kas_akhir NUMERIC,
    total_penjualan_tunai NUMERIC DEFAULT 0,
    total_penjualan_non_tunai NUMERIC DEFAULT 0,
    selisih_kas NUMERIC,
    status TEXT NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.shifts ENABLE ROW LEVEL SECURITY;

-- 5. TRANSACTIONS table
CREATE TABLE public.transactions (
    id BIGINT PRIMARY KEY, -- Sync uses the locally generated ID
    store_id UUID REFERENCES public.stores(id) ON DELETE CASCADE NOT NULL,
    kasir_id BIGINT NOT NULL,
    kasir_nama TEXT NOT NULL,
    tanggal TIMESTAMP WITH TIME ZONE NOT NULL,
    subtotal NUMERIC NOT NULL,
    diskon NUMERIC DEFAULT 0,
    pajak NUMERIC DEFAULT 0,
    service_charge NUMERIC DEFAULT 0,
    total NUMERIC NOT NULL,
    cash_paid NUMERIC NOT NULL,
    cash_change NUMERIC NOT NULL,
    metode_bayar TEXT NOT NULL,
    status TEXT NOT NULL,
    platform TEXT NOT NULL,
    void_reason TEXT,
    shift_id BIGINT REFERENCES public.shifts(id) ON DELETE SET NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;

-- 6. TRANSACTION ITEMS table
CREATE TABLE public.transaction_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaksi_id BIGINT REFERENCES public.transactions(id) ON DELETE CASCADE NOT NULL,
    produk_id BIGINT NOT NULL,
    nama_produk TEXT NOT NULL,
    qty INTEGER NOT NULL,
    harga_satuan NUMERIC NOT NULL,
    varian TEXT DEFAULT 'Normal',
    catatan TEXT
);

ALTER TABLE public.transaction_items ENABLE ROW LEVEL SECURITY;

-- 7. STOCK LOGS table
CREATE TABLE public.stock_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id UUID REFERENCES public.stores(id) ON DELETE CASCADE NOT NULL,
    produk_id BIGINT NOT NULL,
    jenis TEXT CHECK (jenis IN ('IN', 'OUT')) NOT NULL,
    qty INTEGER NOT NULL,
    keterangan TEXT,
    tanggal TIMESTAMP WITH TIME ZONE NOT NULL
);

ALTER TABLE public.stock_logs ENABLE ROW LEVEL SECURITY;
