-- supabase/migrations/006_fix_missing_transactions.sql

-- 1. Ensure the transactions table exists (if it was accidentally deleted or failed to create)
CREATE TABLE IF NOT EXISTS public.transactions (
    id BIGINT PRIMARY KEY,
    store_id UUID,
    kasir_id BIGINT NOT NULL,
    kasir_nama TEXT NOT NULL,
    tanggal TIMESTAMP WITH TIME ZONE NOT NULL,
    subtotal NUMERIC NOT NULL,
    diskon NUMERIC DEFAULT 0,
    pajak NUMERIC DEFAULT 0,
    service_charge NUMERIC DEFAULT 0,
    total NUMERIC NOT NULL,
    cash_paid NUMERIC NOT NULL,
    cash_change NUMERIC NOT NULL,
    metode_bayar TEXT NOT NULL,
    status TEXT NOT NULL,
    platform TEXT NOT NULL,
    void_reason TEXT,
    shift_id BIGINT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Ensure transaction_items table exists
CREATE TABLE IF NOT EXISTS public.transaction_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaksi_id BIGINT NOT NULL,
    produk_id BIGINT NOT NULL,
    nama_produk TEXT NOT NULL,
    qty INTEGER NOT NULL,
    harga_satuan NUMERIC NOT NULL,
    varian TEXT DEFAULT 'Normal',
    catatan TEXT
);

-- 3. Ensure shifts table exists
CREATE TABLE IF NOT EXISTS public.shifts (
    id BIGINT PRIMARY KEY,
    store_id UUID,
    kasir_id BIGINT NOT NULL,
    kasir_nama TEXT NOT NULL,
    waktu_buka TIMESTAMP WITH TIME ZONE NOT NULL,
    waktu_tutup TIMESTAMP WITH TIME ZONE,
    modal_awal NUMERIC NOT NULL,
    kas_akhir NUMERIC,
    total_penjualan_tunai NUMERIC DEFAULT 0,
    total_penjualan_non_tunai NUMERIC DEFAULT 0,
    selisih_kas NUMERIC,
    status TEXT NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Disable Row Level Security so anyone can insert/read
ALTER TABLE public.transactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.transaction_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.shifts DISABLE ROW LEVEL SECURITY;

-- 5. Enable Realtime explicitly for these tables
BEGIN;
  DROP PUBLICATION IF EXISTS supabase_realtime;
  CREATE PUBLICATION supabase_realtime FOR ALL TABLES;
COMMIT;

-- 6. Reload Supabase API Schema Cache (Fixes PGRST205 error)
NOTIFY pgrst, 'reload schema';
